import unreal
import os

"""Import the procedurally baked Erebus PBR textures (Saved/ErebusTextureSource/*.png)
into /Game/Ashes/Textures/Erebus with correct compression/sRGB per map type.

The PNGs are generated by a numpy baker (no downloaded or copyrighted content):
tileable value/Worley noise composites for concrete, metal, mud, asphalt, plus a
damage mask and a flame/smoke erosion noise.
"""

SRC = os.path.join(unreal.Paths.project_saved_dir(), "ErebusTextureSource")
if not os.path.isdir(SRC):
    # Saved/ is gitignored, so a fresh checkout has the .uasset files but none of the
    # PNGs they were imported from. Say so, instead of raising FileNotFoundError from
    # os.listdir three lines down.
    raise SystemExit(
        "[ErebusTex] no source PNGs at " + SRC
        + " -- run `python3 Scripts/BakeErebusTextures.py` first (pure numpy, ~4s, "
          "deterministic; it writes the 15 PNGs this script imports)")
DEST = "/Game/Ashes/Textures/Erebus"
TOOLS = unreal.AssetToolsHelpers.get_asset_tools()

imported = []
for filename in sorted(os.listdir(SRC)):
    if not filename.endswith(".png"):
        continue
    name = filename[:-4]
    task = unreal.AssetImportTask()
    task.filename = os.path.join(SRC, filename)
    task.destination_path = DEST
    task.destination_name = name
    task.automated = True
    task.replace_existing = True
    task.save = False
    TOOLS.import_asset_tasks([task])
    tex = unreal.load_asset(DEST + "/" + name)
    if not tex:
        unreal.log_error("[ErebusTex] import FAILED " + name)
        continue
    if name.endswith("_N"):
        tex.set_editor_property("srgb", False)
        tex.set_editor_property("compression_settings", unreal.TextureCompressionSettings.TC_NORMALMAP)
        tex.set_editor_property("lod_group", unreal.TextureGroup.TEXTUREGROUP_WORLD_NORMAL_MAP)
    elif name.endswith("_D"):
        tex.set_editor_property("srgb", True)
    else:  # roughness / masks / erosion: linear data
        tex.set_editor_property("srgb", False)
        tex.set_editor_property("compression_settings", unreal.TextureCompressionSettings.TC_MASKS)
    unreal.EditorAssetLibrary.save_asset(DEST + "/" + name)
    imported.append(name)

unreal.log("[ErebusTex] imported %d textures: %s" % (len(imported), ", ".join(imported)))
if len(imported) != 15:
    unreal.log_error("[ErebusTex] expected 15 textures, got %d" % len(imported))
